### ISSUE TITLE
ReadMe Tutorial Question

### ISSUE THREAD

**Issue by goatt1167** [juvian/wc3-translate#1]
Hi, I'm new. Thank you for this tool. I'm reading your ReadMe and following your instruction, but having questions.

1. What do you mean by oldTranslated and newUntranslated? Which is newer and which should be changed?
2. Is this tool used after the map file being extracted using MPQEditor?

Thanks again.

**Comment by juvian** [comment]
1. newUntranslated is the string from your new map which you wish you translate (first one in the command). oldTranslated is the string from your second map (which should be the older version you already translated). oldUntranslated is the string from third map (which should be older version before you translated it). If you want to change the translation, the property to use is newTranslated (in my changes from yesterday I now put this property in all strings unlike before). If you keep it empty, the string from oldTranslated will be used. For a map you are translating from scratch (do not have a translated older version), there is no oldTranslated or oldUntranslated so can just fill newTranslated (I will add a guide on this case later).

2.  There is no need to extract files using MPQEditor, I will read map files from mpq directly. In the case it does not work, you can try to extract yourself and using folder instead of mpq. Then after using toWar, you need to put those files into the map using MPQEditor

**Comment by goatt1167** [comment]
Thank you for the fast reply! I'm still trying to figure out how to make it work

I typed 

`node node_modules/wc3-translate/toJson.js "mapPath.w3x" "mapPath.w3x" "mapPath.w3x" output.yaml`

I got this error message

```Initialized StormLib in debug mode
(node:22156) UnhandledPromiseRejectionWarning: Error: Archive could not be opened (error 44)
    at Function.open (C:\Users\jying\OneDrive\Desktop\water水之TD\0\node_modules\@wowserhq\stormjs\dist\mpq.js:130:13)
(node:22156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Did I do something wrong? How can I fix it?

**Comment by juvian** [comment]
Is mapPath.w3x different paths? If its the same map you only need to put it once. Still, it seems the library I use can't read your map, so you will need to extract the files with MPQEditor ("war3map.w3u", "war3map.wts", "war3map.w3a", "war3map.w3t", "war3map.w3h", "war3map.w3q", "war3map.w3b", "war3map.w3d", "war3map.w3i", "war3map.j", "war3mapSkin.txt") and place them in a folder, then use node node_modules/wc3-translate/toJson.js "folderPath1" "folderPath2" "folderPath3" output.yaml

**Comment by goatt1167** [comment]
> Is mapPath.w3x different paths?

No, they are the same path.

And Ok I'll try that. Thank you again.

**Comment by juvian** [comment]
I just added the guide on translating from scratch
