### ISSUE TITLE
I'm getting a partially translated files

### ISSUE THREAD

**Issue by CocoCocoAlx** [juvian/wc3-translate#5]
I'm getting a partially translated files

Hi, I've being used your old script many time ago, and I found this update recently. Reading the instructions, I can obtain a fully translated yaml file, but when I run the last command for create the war3map.* files, some of them (specially war3map.wts) came with a partially translation, even without send error messages. It's like that the program found and error or a mistake and don't continue with translation and left the rest of the file untranslated. What I'm doing wrong?

Extra: I'have using Node and NPM in Linux, specificily:
OS: Debian GNU/Linux
NPM: 8.18.0
Node: v18.7.0

Many, many thanks for your work!

**Comment by CocoCocoAlx** [comment]
Sorry, here I upload an image as reference:
![imagen](https://user-images.githubusercontent.com/17306026/187122529-bff47301-4036-472f-af1a-35c509af4080.png)

**Comment by juvian** [comment]
yeah I don't particularly translate wts file. Wts file is a file with strings that you can then reference in other files like script, units, abilities and such. I take the reference and "inline" the translation there. So instead of leaving the TRIGSTR_ reference, I read the string in WTS file and replace it with it. I do this mainly for 2 reasons: WTS parsing is really slow in older warcraft, and it allows translating a sentence that was maybe used multiple times in different places as different strings. The only things I translate in wts file are the strings I find no references, which should mean it is not used and there is no need to translate it but just in case I do. But yeah you can just ignore that file, in game you should see all translated

**Comment by CocoCocoAlx** [comment]
Well... I've been probing translate 2 different campaigns with opposite results at this moment. One has got fully translated, but other still having texts on original language, but I have a better approach to understand how this program works. So I will close this issue. Many thanks for aswering so soon. Lok'tar!

**Comment by juvian** [comment]
There are many reasons it can keep text in original language (slk bugs, my script not picking up that string to be translated, translator not translating). A first step would be to find the non translated text in yaml file. If its not there then my script is not picking it up when it should. But probably better to contact me via discord juvian#4621
